services:
    server:
        build:
            context: .
        env_file:
            - .env
        environment:
            NODE_ENV: production
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
        ports:
            - ${PORT}:${PORT}
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started

    mysql:
        image: mysql:8.4
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        healthcheck:
            test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        image: redis:7.4.2
        ports:
            - 6379:6379
        restart: always
